# Generated by Django 5.1.5 on 2025-01-29 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Назва книги')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('author', models.CharField(max_length=150, verbose_name='Автор')),
                ('quantity', models.PositiveIntegerField(db_default=1, verbose_name='Quantity')),
                ('published_year', models.PositiveBigIntegerField(verbose_name='Рік видання')),
                ('language', models.CharField(choices=[('EN', 'English'), ('UK', 'Ukrainian'), ('RU', 'Russian'), ('FR', 'French'), ('DE', 'German')], max_length=2, verbose_name='Мова')),
                ('number_of_pages', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Кількість сторінок')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Опис')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'Книги',
                'db_table': 'book',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='book_images', verbose_name='Зображення')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='books.book')),
            ],
            options={
                'db_table': 'book_images',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Жанр')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('position', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='books.genre', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанри',
                'db_table': 'genre',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.genre', verbose_name='Жанр'),
        ),
    ]
