# Generated by Django 5.1.5 on 2025-01-30 11:02

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Автор')),
                ('age', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Автори',
                'db_table': 'author',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_default='Unknown Publisher', max_length=150, unique=True, verbose_name='Видавець')),
            ],
            options={
                'verbose_name': 'Видавець',
                'verbose_name_plural': 'Видавці',
                'db_table': 'publisher',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='books.author'),
        ),
        migrations.CreateModel(
            name='DEliveryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_option', models.CharField(choices=[('pick_up', 'Ready to Pick Up'), ('delivering', 'Can Be DElivered')], default='pick_up', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_options', to='books.book')),
                ('city', smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveryoption_city', to='cities_light.city', verbose_name='City (Single)')),
                ('city_multiple', smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='region_multiple', chained_model_field='region', related_name='deliveryoption_multiple_city', to='cities_light.city', verbose_name='City (Multiple)')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.country', verbose_name='Країна')),
                ('region', smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveryoption_single', to='cities_light.region', verbose_name='Region (Single)')),
                ('region_multiple', smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='country', chained_model_field='country', related_name='deliveryoption_multiple', to='cities_light.region', verbose_name='Region (Multiple)')),
            ],
            options={
                'verbose_name': 'Варіант доставки',
                'verbose_name_plural': 'Варіанти доставки',
                'db_table': 'delivery_option',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.publisher'),
            preserve_default=False,
        ),
    ]
