# Generated by Django 5.1.6 on 2025-02-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('draft', 'Draft'), ('inactive', 'Inactive')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='deliveryoption',
            name='delivery_option',
            field=models.CharField(choices=[('pick_up', 'Готов до видачі'), ('delivering', 'Може бути доставлений')], default='pick_up', max_length=20),
        ),
    ]
