# Generated by Django 5.1.6 on 2025-02-09 17:22

import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=model_utils.fields.StatusField(choices=[('draft', 'Draft'), ('pending', 'Pending Confirmation'), ('active', 'Active'), ('unactive', 'Inactive'), ('rejected', 'Rejected')], default='pending', max_length=100, no_check_for_status=True),
        ),
    ]
