# Generated by Django 5.1.6 on 2025-02-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, help_text='Детальний опис книги', null=True, verbose_name='Опис'),
        ),
    ]
