# Generated by Django 5.1.6 on 2025-02-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_rename_book_cart_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartQueryset',
        ),
    ]
