# Generated by Django 5.1.6 on 2025-02-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_address_order_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
